export const myCards = [
    // КРУПНЫЙ ПЛАН
    {id: 1, src: require('../img/prev/close_up/3.jpg'), w: '', h: ''},
    {id: 2, src: require('../img/prev/close_up/4.jpg'), w: '', h: ''},
    {id: 3, src: require('../img/prev/close_up/8.jpg'), w: '', h: ''},
    {id: 4, src: require('../img/prev/close_up/2.jpg'), w: '', h: ''},
    {id: 5, src: '', w: '', h: ''},
    {id: 6, src: require('../img/prev/close_up/7.jpg'), w: '', h: ''},
    {id: 7, src: '', w: 'auto', h: 'inherit'},
    {id: 8, src: '', w: 'auto', h: 'inherit'},
    {id: 9, src: require('../img/prev/close_up/1.jpg'), w: '', h: ''},
    {id: 10, src: '', w: '', h: ''},
    {id: 11, src: require('../img/prev/close_up/10.jpg'), w: 'auto', h: 'inherit'},
    {id: 12, src: require('../img/prev/close_up/6.jpg'), w: 'auto', h: 'inherit'},
    
    // СРЕДНИЙ ПЛАН
    {id: 13, src: '', w: 'auto', h: 'inherit'},
    {id: 14, src: require('../img/prev/middle/5.jpg'), w: '', h: ''},
    {id: 15, src: '', w: 'auto', h: 'inherit'},
    {id: 16, src: require('../img/prev/middle/2.jpg'), w: '', h: ''},
    {id: 17, src: '', w: 'auto', h: 'inherit'},
    {id: 18, src: '', w: 'auto', h: 'inherit'},
    {id: 19, src: '', w: '', h: ''},
    {id: 20, src: '', w: 'auto', h: 'inherit'},
    {id: 21, src: '', w: '', h: ''},
    {id: 22, src: '', w: 'auto', h: 'inherit'},
    {id: 23, src: '', w: 'auto', h: 'inherit'},
    {id: 24, src: require('../img/prev/middle/13.jpg'), w: '', h: ''},
    
    {id: 25, src: '', w: 'auto', h: 'inherit'},
    {id: 26, src: '', w: 'auto', h: 'inherit'},
    {id: 27, src: '', w: 'auto', h: 'inherit'},
    {id: 28, src: '', w: '', h: ''},
    {id: 29, src: require('../img/prev/middle/11.jpg'), w: '', h: ''},
    {id: 30, src: '', w: '', h: ''},
    {id: 31, src: '', w: '', h: ''},
    {id: 32, src: '', w: 'auto', h: 'inherit'},
    {id: 33, src: '', w: '', h: ''},
    {id: 34, src: '', w: '', h: ''},
    {id: 35, src: '', w: '', h: ''},
    {id: 36, src: '', w: '', h: ''},

    // ДАЛЬНИЙ ПЛАН
    {id: 37, src: '', w: 'auto', h: 'inherit'},
    {id: 38, src: '', w: 'auto', h: 'inherit'},
    {id: 39, src: '', w: '', h: ''},
    {id: 40, src: '', w: '', h: ''},
    {id: 41, src: require('../img/prev/wide/3.jpg'), w: '', h: ''},
    {id: 42, src: '', w: '', h: ''},
    {id: 43, src: '', w: 'auto', h: 'inherit'},
    {id: 44, src: '', w: 'auto', h: 'inherit'},
    {id: 45, src: '', w: '', h: ''},
    {id: 46, src: '', w: 'auto', h: 'inherit'},
    {id: 47, src: '', w: 'auto', h: 'inherit'},
    {id: 48, src: '', w: '', h: ''},

    // ПОРТРЕТЫ
    {id: 49, src: '', w: '', h: ''},
    {id: 50, src: '', w: '', h: ''},
    {id: 51, src: '', w: '', h: ''},
    {id: 52, src: '', w: 'auto', h: 'inherit'},
    {id: 53, src: '', w: '', h: ''},
    {id: 54, src: '', w: '', h: ''},
    {id: 55, src: '', w: 'auto', h: 'inherit'},
    {id: 56, src: '', w: '', h: ''},
    {id: 57, src: '', w: '', h: ''},
    {id: 58, src: '', w: 'auto', h: 'inherit'},
    {id: 59, src: '', w: '', h: ''},
    {id: 60, src: '', w: '', h: ''},

    // АБСТРАКТНОЕ - НЕ ЛЮДИ
    {id: 61, src: require('../img/prev/abstract/1.jpg'), w: 'auto', h: 'inherit'},
    {id: 62, src: require('../img/prev/abstract/2.jpg'), w: 'auto', h: 'inherit'},
    {id: 63, src: require('../img/prev/abstract/4.jpg'), w: '', h: ''},
    {id: 64, src: '', w: '', h: ''},
    {id: 65, src: require('../img/prev/abstract/5.jpg'), w: 'auto', h: 'inherit'},
    {id: 66, src: require('../img/prev/abstract/6.jpg'), w: 'auto', h: 'inherit'},
    {id: 67, src: '', w: 'auto', h: 'inherit'},
    {id: 68, src: '', w: 'auto', h: 'inherit'},
    {id: 69, src: require('../img/prev/abstract/3.jpg'), w: '', h: ''},
    {id: 70, src: '', w: 'auto', h: 'inherit'},
    {id: 71, src: '', w: 'auto', h: 'inherit'},
    {id: 72, src: '', w: 'auto', h: 'inherit'},


    // СЕТКА 100
    {id: 100, 
        src: require('../img/main/218.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '',
        engagement: '41%  вт  3:40',
        currStatistic: {
            1: {period: '05.02', subs: '67', nonsubs: '17', profile: '13', main: '67', other: '17'},
            2: {period: '30.01', subs: '67', nonsubs: '15', profile: '9', main: '67', other: '17'},
        }
    },
    {id: 101, 
        src: require('../img/main/4.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '',
        engagement: '41%  вт  3:40',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '78', nonsubs: '140', profile: '368', main: '-', other: '1'},
            2: {period: '24.01', subs: '77', nonsubs: '141', profile: '367', main: '-', other: '1'},
        }
    },
    {id: 102, 
        src: require('../img/main/56.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '21%  ср  2:50',
        currStatistic: {
            1: {period: '05.02', subs: '69', nonsubs: '32', profile: '65', main: '60', other: '2'},
            2: {period: '30.01', subs: '67', nonsubs: '31', profile: '57', main: '60', other: '2'},
        }
    },
    {id: 103, src: '', w: '', h: ''},


    {id: 399, 
        src: require('../img/main/224.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '06.02', subs: '23', nonsubs: '1', profile: '1', main: '24', other: '-'},
        }
    },
    {id: 400, 
        src: require('../img/main/223.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '58', nonsubs: '7', profile: '1', main: '63', other: '9'},
        }
    },
    {id: 401, 
        src: require('../img/main/222.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '63', nonsubs: '2', profile: '6', main: '64', other: '1'},
            2: {period: '30.01', subs: '26', nonsubs: '0', profile: '-', main: '26', other: '-'},
        }
    },
    {id: 402, 
        src: require('../img/main/220.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '57', nonsubs: '3', profile: '11', main: '66', other: '1'},
            2: {period: '30.01', subs: '56', nonsubs: '2', profile: '7', main: '66', other: '1'},
        }
    },
    {id: 403, 
        src: require('../img/main/219.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '51', nonsubs: '3', profile: '11', main: '55', other: '4'},
            2: {period: '30.01', subs: '49', nonsubs: '3', profile: '8', main: '55', other: '4'},
        }
    },
    {id: 404, 
        src: require('../img/main/217.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '65', nonsubs: '33', profile: '21', main: '67', other: '27'},
            2: {period: '30.01', subs: '65', nonsubs: '33', profile: '18', main: '67', other: '27'},
        }
    },
    {id: 405, 
        src: require('../img/main/216.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '42', nonsubs: '17', profile: '29', main: '35', other: '2'},
            2: {period: '30.01', subs: '41', nonsubs: '17', profile: '26', main: '35', other: '2'},
        }
    },
    {id: 407, 
        src: require('../img/main/214.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '05.02', subs: '57', nonsubs: '20', profile: '32', main: '56', other: '1'},
            2: {period: '30.01', subs: '56', nonsubs: '19', profile: '28', main: '56', other: '1'},
        }
    },
    {id: 411, 
        src: require('../img/main/80.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '51', nonsubs: '21', profile: '29', main: '48', other: '3'},
            2: {period: '30.01', subs: '50', nonsubs: '20', profile: '25', main: '48', other: '3'},
        }
    },
    {id: 414, 
        src: require('../img/main/77.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '49', nonsubs: '20', profile: '40', main: '47', other: '2'},
            2: {period: '30.01', subs: '48', nonsubs: '20', profile: '37', main: '47', other: '2'},
        }
    },
    {id: 417, 
        src: require('../img/main/74.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '36', nonsubs: '18', profile: '38', main: '37', other: '4'},
            2: {period: '30.01', subs: '35', nonsubs: '18', profile: '34', main: '37', other: '4'},
        }
    },
    {id: 418, 
        src: require('../img/main/72.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '42', nonsubs: '17', profile: '33', main: '42', other: '3'},
            2: {period: '15.01-30.01', subs: '40', nonsubs: '17', profile: '29', main: '42', other: '3'},
        }
    },

    {id: 419, 
        src: require('../img/main/71.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '60', nonsubs: '20', profile: '34', main: '64', other: '1'},
            2: {period: '15.01-30.01', subs: '58', nonsubs: '20', profile: '30', main: '64', other: '1'},
        }
    },
    {id: 422, 
        src: require('../img/main/68.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '57', nonsubs: '23', profile: '41', main: '59', other: '5'},
            2: {period: '24.01-30.01', subs: '56', nonsubs: '23', profile: '39', main: '59', other: '5'},
        }
    },
    {id: 425, 
        src: require('../img/main/64.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '28%  вс 7:01',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '53', nonsubs: '18', profile: '34', main: '47', other: '3'},
            2: {period: '15.01-24.01', subs: '53', nonsubs: '18', profile: '33', main: '47', other: '3'},
        }
    },
    {id: 429, 
        src: require('../img/main/58.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '19%  пн  3:40',
        currStatistic: {
            1: {period: '05.02', subs: '56', nonsubs: '20', profile: '31', main: '53', other: '2'},
            2: {period: '15.01-30.01', subs: '56', nonsubs: '19', profile: '30', main: '53', other: '2'},
        }
    },
    {id: 432, 
        src: require('../img/main/54.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '13%  чт  5:25',
        currStatistic: {
            1: {period: '05.02', subs: '49', nonsubs: '23', profile: '35', main: '45', other: '3'},
            2: {period: '30.01', subs: '49', nonsubs: '22', profile: '34', main: '45', other: '3'},
        }
    },
    {id: 436, 
        src: require('../img/main/50.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '29%  сб  3:10',
        currStatistic: {
            1: {period: '05.02', subs: '56', nonsubs: '36', profile: '59', main: '50', other: '3'},
            2: {period: '30.01', subs: '56', nonsubs: '35', profile: '57', main: '50', other: '3'},
        }
    },
    {id: 438,
        src: require('../img/main/48.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '27%  ср  6:31',
        currStatistic: {
            1: {period: '05.02', subs: '51', nonsubs: '28', profile: '47', main: '51', other: '-'},
            2: {period: '30.01', subs: '51', nonsubs: '27', profile: '45', main: '51', other: '-'},
        }
    },
    {id: 439, 
        src: require('../img/main/47.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '30%  сб  7:27',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '51', nonsubs: '25', profile: '42', main: '52', other: '7'},
            2: {period: '24.01', subs: '51', nonsubs: '24', profile: '41', main: '52', other: '7'},
        }
    },
    {id: 441, 
        src: require('../img/main/44.jpg'), 
        w: '', 
        h: '', 
        text: '', tags: '', 
        engagement: '22%  пн  2:40',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '45', nonsubs: '21', profile: '42', main: '45', other: '1'},
            2: {period: '15.01-24.01', subs: '45', nonsubs: '21', profile: '41', main: '45', other: '1'},
        }
    },
    {id: 445, 
        src: require('../img/main/33.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '29%  вт  5:26',
        currStatistic: {
            1: {period: '06.02', subs: '68', nonsubs: '6', profile: '12', main: '68', other: '1'},
        }
    },
    {id: 446, 
        src: require('../img/main/30.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '',
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '72', nonsubs: '37', profile: '61', main: '70', other: '23'},
            2: {period: '08.12-08.01', subs: '71', nonsubs: '37', profile: '60', main: '70', other: '23'}, 
        }
    },
    {id: 448, 
        src: require('../img/main/27.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  пт  8:40',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '57', nonsubs: '37', profile: '93', main: '38', other: '4'},
            2: {period: '24.01', subs: '57', nonsubs: '37', profile: '92', main: '38', other: '4'},
        }
    },

    {id: 449, 
        src: require('../img/main/29.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '20%  чт  8:40',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '77', nonsubs: '32', profile: '77', main: '61', other: '2'},
            2: {period: '15.01-24.01', subs: '77', nonsubs: '32', profile: '76', main: '61', other: '2'},
        }
    },
    {id: 450, 
        src: require('../img/main/26.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '22%  чт  1:15',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '54', nonsubs: '29', profile: '64', main: '36', other: '1'}, 
            2: {period: '08.12-08.01', subs: '54', nonsubs: '27', profile: '62', main: '36', other: '1'}, 
        }
    },
    {id: 451, 
        src: require('../img/main/28.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '22%  ср  2:50',
        currStatistic: {
            1: {period: '24.01-05.02', subs: '55', nonsubs: '30', profile: '72', main: '36', other: '1'},
            2: {period: '15.01', subs: '55', nonsubs: '30', profile: '71', main: '36', other: '1'},
        }
    },
    {id: 452, 
        src: require('../img/main/23.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '20%  вт  3:15',
        currStatistic: {
            1: {period: '24.01-05.02', subs: '65', nonsubs: '31', profile: '73', main: '63', other: '-'},
            2: {period: '15.01', subs: '65', nonsubs: '31', profile: '72', main: '63', other: '-'},
        }
    },
    {id: 453, 
        src: require('../img/main/20.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '24.01-05.02', subs: '60', nonsubs: '32', profile: '82', main: '35', other: '5'},
            2: {period: '15.01', subs: '60', nonsubs: '32', profile: '81', main: '35', other: '5'},
        }
    },
    {id: 454, 
        src: require('../img/main/21.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  пн  3:20',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '70', nonsubs: '25', profile: '64', main: '52', other: '1'}, 
            2: {period: '08.12-08.01', subs: '69', nonsubs: '25', profile: '63', main: '52', other: '1'},
        }
    },
    {id: 455, 
        src: require('../img/main/18.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '31%  сб  11:19',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '74', nonsubs: '24', profile: '68', main: '59', other: '5'},
            2: {period: '15.01-24.01', subs: '74', nonsubs: '23', profile: '67', main: '59', other: '5'},
        }
    },
    {id: 457, 
        src: require('../img/main/7.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '91', nonsubs: '49', profile: '127', main: '88', other: '3'},
            2: {period: '15.01-24.01', subs: '91', nonsubs: '49', profile: '126', main: '88', other: '3'},
        }
    },
    {id: 458, 
        src: require('../img/main/8.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  вт  4:10',
        currStatistic: {
            1: {period: '05.02', subs: '77', nonsubs: '47', profile: '125', main: '59', other: '1'},
            2: {period: '30.01', subs: '77', nonsubs: '46', profile: '124', main: '59', other: '1'},
        }
    },
    {id: 461, 
        src: require('../img/main/5.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '05.02', subs: '87', nonsubs: '54', profile: '117', main: '81', other: '9'},
            2: {period: '15.01-30.01', subs: '87', nonsubs: '53', profile: '116', main: '81', other: '9'},
        }
    },
    {id: 462, 
        src: require('../img/main/11.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '05.02', subs: '89', nonsubs: '59', profile: '131', main: '75', other: '12'},
            2: {period: '15.01-30.01', subs: '89', nonsubs: '58', profile: '130', main: '75', other: '11'},
        }
    },
    {id: 465, 
        src: require('../img/main/12.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '24%  чт  8:10',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '104', nonsubs: '94', profile: '199', main: '95', other: '25'},
            2: {period: '02.01-08.01', subs: '103', nonsubs: '94', profile: '198', main: '95', other: '25'},
        }
    },
    {id: 466, 
        src: require('../img/main/13.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '25%  ср  3:17',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '108', nonsubs: '78', profile: '184', main: '88', other: '6'},
            2: {period: '15.01-24.01', subs: '108', nonsubs: '77', profile: '183', main: '88', other: '6'},
        }
    },
    {id: 467, 
        src: require('../img/main/3.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '121', nonsubs: '122', profile: '393', main: '88', other: '13'},
            2: {period: '15.01-24.01', subs: '121', nonsubs: '121', profile: '392', main: '88', other: '13'},
        }
    },
    {id: 468, 
        src: require('../img/main/15.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '15%  вт  11:26',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '94', nonsubs: '149', profile: '305', main: '47', other: '20'},
            2: {period: '15.01-24.01', subs: '94', nonsubs: '148', profile: '304', main: '47', other: '20'},
        }
    },
    {id: 469, 
        src: require('../img/main/17.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '16%  чт  12:01',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '82', nonsubs: '140', profile: '315', main: '41', other: '10'},
            2: {period: '02.01-08.01', subs: '81', nonsubs: '140', profile: '313', main: '41', other: '10'},
        }
    },

    {id: 470, 
        src: require('../img/main/221.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '83', nonsubs: '96', profile: '194', main: '74', other: '4'}, 
            2: {period: '02.01-08.01', subs: '82', nonsubs: '96', profile: '192', main: '74', other: '4'},
        }
    },


    {id: 471, 
        src: require('../img/main/182.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '71', nonsubs: '97', profile: '178', main: '59', other: '5'},
            2: {period: '02.01-08.01', subs: '70', nonsubs: '97', profile: '177', main: '59', other: '5'},
        }
    },
    {id: 472, 
        src: require('../img/main/183.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '89', nonsubs: '120', profile: '231', main: '67', other: '4'},
            2: {period: '02.01-08.01', subs: '87', nonsubs: '120', profile: '229', main: '67', other: '4'},
        }
    },
    {id: 473, 
        src: require('../img/main/184.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '103', nonsubs: '113', profile: '251', main: '99', other: '3'},
            2: {period: '02.01-08.01', subs: '102', nonsubs: '113', profile: '249', main: '99', other: '3'},
        }
    },
    ///////
    {id: 474, 
        src: require('../img/main/185.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '100', nonsubs: '124', profile: '292', main: '156', other: '2'},
            2: {period: '02.01-08.01', subs: '99', nonsubs: '124', profile: '291', main: '156', other: '2'},
        }
    },
    {id: 475, 
        src: require('../img/main/186.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-05.02', subs: '96', nonsubs: '129', profile: '279', main: '98', other: '16'},
            2: {period: '15.01', subs: '95', nonsubs: '128', profile: '277', main: '98', other: '16'},
        }
    },
    {id: 476, 
        src: require('../img/main/187.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-05.02', subs: '83', nonsubs: '238', profile: '257', main: '40', other: '9'},
            2: {period: '15.01', subs: '82', nonsubs: '237', profile: '255', main: '40', other: '9'},
        }
    },
    {id: 477, 
        src: require('../img/main/188.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '83', nonsubs: '267', profile: '210', main: '43', other: '7'},
            2: {period: '02.01-08.01', subs: '82', nonsubs: '267', profile: '209', main: '43', other: '7'},
        }
    },
    {id: 478, 
        src: require('../img/main/189.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '63', nonsubs: '117', profile: '260', main: '-', other: '2'},
            2: {period: '15.01-30.01', subs: '66', nonsubs: '118', profile: '266', main: '-', other: '2'},
        }
    },
    {id: 479, 
        src: require('../img/main/190.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '56', nonsubs: '82', profile: '174', main: '-', other: '3'},
            2: {period: '08.01', subs: '55', nonsubs: '82', profile: '174', main: '-', other: '3'}, 
        }
    },
    {id: 480, 
        src: require('../img/main/191.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '55', nonsubs: '77', profile: '166', main: '-', other: '1'},
            2: {period: '08.01', subs: '54', nonsubs: '77', profile: '166', main: '-', other: '1'},
        }
    },
    {id: 481, 
        src: require('../img/main/192.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '05.02', subs: '29', nonsubs: '52', profile: '102', main: '-', other: '-'},
            2: {period: '15.01-30.01', subs: '30', nonsubs: '53', profile: '108', main: '-', other: '-'},
        }
    },
    {id: 482, 
        src: require('../img/main/193.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '42', nonsubs: '71', profile: '143', main: '-', other: '1'},
            2: {period: '08.01', subs: '41', nonsubs: '73', profile: '145', main: '-', other: '1'}, 
        }
    },
    {id: 483, 
        src: require('../img/main/194.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '41', nonsubs: '87', profile: '156', main: '-', other: '5'},
            2: {period: '15.01-24.01', subs: '41', nonsubs: '89', profile: '158', main: '-', other: '5'},
        }
    },
    {id: 484, 
        src: require('../img/main/195.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '32', nonsubs: '90', profile: '180', main: '-', other: '2'},
            2: {period: '15.01-24.01', subs: '33', nonsubs: '94', profile: '188', main: '-', other: '2'},
        }
    },
    {id: 485, 
        src: require('../img/main/196.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '47', nonsubs: '86', profile: '197', main: '-', other: '-'},
            2: {period: '15.01-24.01', subs: '47', nonsubs: '87', profile: '200', main: '-', other: '-'},
        }
    },
    {id: 486, 
        src: require('../img/main/197.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '33', nonsubs: '34', profile: '81', main: '-', other: '2'}, 
            2: {period: '08.01', subs: '32', nonsubs: '37', profile: '83', main: '-', other: '2'},
        }
    },
    {id: 487, 
        src: require('../img/main/198.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '32', nonsubs: '29', profile: '76', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '31', nonsubs: '32', profile: '78', main: '-', other: '-'},
        }
    },
    {id: 488, 
        src: require('../img/main/199.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '30', nonsubs: '35', profile: '87', main: '-', other: '3'}, 
            2: {period: '08.01', subs: '29', nonsubs: '36', profile: '89', main: '-', other: '3'},
        }
    },
    {id: 489, 
        src: require('../img/main/200.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '29', nonsubs: '25', profile: '74', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '28', nonsubs: '26', profile: '76', main: '-', other: '-'},
        }
    },
    {id: 490, 
        src: require('../img/main/201.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '32', nonsubs: '26', profile: '77', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '31', nonsubs: '27', profile: '79', main: '-', other: '1'},
        }
    },
    {id: 491, 
        src: require('../img/main/202.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '28', nonsubs: '39', profile: '92', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '28', nonsubs: '39', profile: '95', main: '-', other: '1'},
        }
    },
    {id: 492, 
        src: require('../img/main/203.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '32', nonsubs: '35', profile: '86', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '31', nonsubs: '35', profile: '88', main: '-', other: '-'},
        }
    },
    {id: 493, 
        src: require('../img/main/204.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '27', nonsubs: '34', profile: '76', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '26', nonsubs: '35', profile: '78', main: '-', other: '-'},
        }
    },
    ////////
    {id: 494, 
        src: require('../img/main/205.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '29', nonsubs: '28', profile: '72', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '29', nonsubs: '29', profile: '74', main: '-', other: '1'},
        }
    },
    {id: 495, 
        src: require('../img/main/206.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '23', nonsubs: '17', profile: '46', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '22', nonsubs: '19', profile: '47', main: '-', other: '-'},
        }
    },
    {id: 496, 
        src: require('../img/main/208.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '27', nonsubs: '36', profile: '78', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '27', nonsubs: '36', profile: '79', main: '-', other: '1'},
        }
    },
    {id: 497, 
        src: require('../img/main/209.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-05.02', subs: '27', nonsubs: '37', profile: '90', main: '-', other: '1'},
            2: {period: '08.01', subs: '26', nonsubs: '37', profile: '88', main: '-', other: '1'},
        }
    },
    {id: 498, 
        src: require('../img/main/210.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01-05.02', subs: '9', nonsubs: '12', profile: '22', main: '-', other: '-'},
            2: {period: '15.01-24.01', subs: '8', nonsubs: '12', profile: '21', main: '-', other: '-'},
        }
    },
    {id: 499, 
        src: require('../img/main/212.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '-', nonsubs: '-', profile: '-', main: '51', other: '-'},
            2: {period: '15.01-24.01', subs: '-', nonsubs: '-', profile: '-', main: '52', other: '-'},
        }
    },
]