export const myCards = [
    {id: 1, src: require('../img/prev/1.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 2, src: require('../img/prev/3.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 3, src: require('../img/prev/13.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 4, src: require('../img/prev/17.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 5, src: require('../img/prev/11.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 6, src: require('../img/prev/7.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 7, src: require('../img/prev/16.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 8, src: require('../img/prev/15.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 9, src: require('../img/prev/12.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 10, src: require('../img/prev/17.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 11, src: require('../img/prev/8.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 12, src: require('../img/prev/14.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 13, src: require('../img/prev/13.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 14, src: require('../img/prev/10.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 15, src: require('../img/prev/9.jpg'), w: '', h: '', text: '', tags: ''},

    {id: 16, src: require('../img/main/4.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 17, src: require('../img/main/5.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 18, src: require('../img/main/3.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 19, src: '', w: '', h: '', text: '', tags: ''},
    {id: 20, src: require('../img/main/7.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 21, src: require('../img/main/8.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 22, src: require('../img/main/9.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 23, src: require('../img/main/10.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 24, src: require('../img/main/11.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 25, src: require('../img/main/12.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 26, src: require('../img/main/13.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 27, src: require('../img/main/14.jpg'), w: 'auto', h: 'inherit', text: '', tags: ''},
    {id: 28, src: require('../img/main/15.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 29, src: require('../img/main/16.jpg'), w: '', h: '', text: '', tags: ''},
    {id: 30, src: require('../img/main/17.jpg'), w: '', h: '', text: '', tags: ''},
    
    {id: 31, src: require('../img/backet.png'), w: '6vw', h: 'auto', text: '', tags: ''}
]