export const myCards = [
    // КРУПНЫЙ ПЛАН
    {id: 1, src: require('../img/prev/close_up/3.jpg'), w: '', h: ''},
    {id: 2, src: require('../img/prev/close_up/4.jpg'), w: '', h: ''},
    {id: 3, src: require('../img/prev/close_up/8.jpg'), w: '', h: ''},
    {id: 4, src: require('../img/prev/close_up/2.jpg'), w: '', h: ''},
    {id: 5, src: '', w: '', h: ''},
    {id: 6, src: require('../img/prev/close_up/7.jpg'), w: '', h: ''},
    {id: 7, src: '', w: 'auto', h: 'inherit'},
    {id: 8, src: '', w: 'auto', h: 'inherit'},
    {id: 9, src: require('../img/prev/close_up/1.jpg'), w: '', h: ''},
    {id: 10, src: '', w: '', h: ''},
    {id: 11, src: require('../img/prev/close_up/10.jpg'), w: 'auto', h: 'inherit'},
    {id: 12, src: require('../img/prev/close_up/6.jpg'), w: 'auto', h: 'inherit'},
    
    // СРЕДНИЙ ПЛАН
    {id: 13, src: '', w: 'auto', h: 'inherit'},
    {id: 14, src: require('../img/prev/middle/5.jpg'), w: '', h: ''},
    {id: 15, src: require('../img/prev/middle/6.jpg'), w: 'auto', h: 'inherit'},
    {id: 16, src: require('../img/prev/middle/2.jpg'), w: '', h: ''},
    {id: 17, src: require('../img/prev/middle/3.jpg'), w: '', h: ''},
    {id: 18, src: '', w: '', h: ''},
    {id: 19, src: require('../img/prev/middle/1.jpg'), w: '', h: ''},
    {id: 20, src: '', w: 'auto', h: 'inherit'},
    {id: 21, src: '', w: '', h: ''},
    {id: 22, src: '', w: 'auto', h: 'inherit'},
    {id: 23, src: require('../img/prev/middle/7.jpg'), w: 'auto', h: 'inherit'},
    {id: 24, src: '', w: '', h: ''},
    
    {id: 25, src: '', w: 'auto', h: 'inherit'},
    {id: 26, src: '', w: '', h: ''},
    {id: 27, src: '', w: 'auto', h: 'inherit'},
    {id: 28, src: '', w: '', h: ''},
    {id: 29, src: require('../img/prev/middle/11.jpg'), w: '', h: ''},
    {id: 30, src: '', w: '', h: ''},
    {id: 31, src: '', w: '', h: ''},
    {id: 32, src: '', w: 'auto', h: 'inherit'},
    {id: 33, src: '', w: '', h: ''},
    {id: 34, src: '', w: '', h: ''},
    {id: 35, src: '', w: '', h: ''},
    {id: 36, src: '', w: '', h: ''},

    // ДАЛЬНИЙ ПЛАН
    {id: 37, src: '', w: 'auto', h: 'inherit'},
    {id: 38, src: '', w: 'auto', h: 'inherit'},
    {id: 39, src: require('../img/prev/wide/2.jpg'), w: '', h: ''},
    {id: 40, src: '', w: '', h: ''},
    {id: 41, src: require('../img/prev/wide/3.jpg'), w: '', h: ''},
    {id: 42, src: require('../img/prev/wide/4.jpg'), w: '', h: ''},
    {id: 43, src: '', w: 'auto', h: 'inherit'},
    {id: 44, src: '', w: 'auto', h: 'inherit'},
    {id: 45, src: '', w: '', h: ''},
    {id: 46, src: '', w: 'auto', h: 'inherit'},
    {id: 47, src: '', w: 'auto', h: 'inherit'},
    {id: 48, src: '', w: '', h: ''},

    // ПОРТРЕТЫ
    {id: 49, src: '', w: '', h: ''},
    {id: 50, src: '', w: '', h: ''},
    {id: 51, src: '', w: '', h: ''},
    {id: 52, src: '', w: 'auto', h: 'inherit'},
    {id: 53, src: '', w: '', h: ''},
    {id: 54, src: '', w: '', h: ''},
    {id: 55, src: '', w: 'auto', h: 'inherit'},
    {id: 56, src: require('../img/prev/portrait/6.jpg'), w: '', h: ''},
    {id: 57, src: '', w: '', h: ''},
    {id: 58, src: '', w: 'auto', h: 'inherit'},
    {id: 59, src: '', w: '', h: ''},
    {id: 60, src: '', w: '', h: ''},

    // АБСТРАКТНОЕ - НЕ ЛЮДИ
    {id: 61, src: require('../img/prev/abstract/1.jpg'), w: '', h: ''},
    {id: 62, src: require('../img/prev/abstract/2.jpg'), w: 'auto', h: 'inherit'},
    {id: 63, src: require('../img/prev/abstract/4.jpg'), w: '', h: ''},
    {id: 64, src: require('../img/prev/abstract/5.jpg'), w: '', h: ''},
    {id: 65, src: '', w: 'auto', h: 'inherit'},
    {id: 66, src: require('../img/prev/abstract/6.jpg'), w: 'auto', h: 'inherit'},
    {id: 67, src: '', w: 'auto', h: 'inherit'},
    {id: 68, src: '', w: 'auto', h: 'inherit'},
    {id: 69, src: require('../img/prev/abstract/3.jpg'), w: '', h: ''},
    {id: 70, src: '', w: 'auto', h: 'inherit'},
    {id: 71, src: '', w: 'auto', h: 'inherit'},
    {id: 72, src: '', w: 'auto', h: 'inherit'},


    // СЕТКА 100
    {id: 100, 
        src: require('../img/main/218.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '',
        engagement: '41%  вт  3:40',
        currStatistic: {
            1: {period: '30.01', subs: '67', nonsubs: '15', profile: '9', main: '67', other: '17'},
            2: {period: '24.01', subs: '66', nonsubs: '15', profile: '8', main: '67', other: '17'},
            3: {period: '15.01', subs: '65', nonsubs: '15', profile: '6', main: '67', other: '17'},
            4: {period: '08.01', subs: '64', nonsubs: '15', profile: '4', main: '67', other: '17'},
            5: {period: '29.12-02.01', subs: '64', nonsubs: '15', profile: '3', main: '67', other: '17'},
            6: {period: '17.12', subs: '64', nonsubs: '15', profile: '2', main: '67', other: '17'}, 
            7: {period: '12.12', subs: '55', nonsubs: '15', profile: '1', main: '58', other: '17'}, 
            8: {period: '10.12', subs: '47', nonsubs: '15', profile: '1', main: '47', other: '16'}
        }
    },
    {id: 101, 
        src: require('../img/main/4.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '',
        engagement: '41%  вт  3:40',
        currStatistic: {
            1: {period: '30.01', subs: '78', nonsubs: '141', profile: '368', main: '-', other: '1'},
            2: {period: '24.01', subs: '77', nonsubs: '141', profile: '367', main: '-', other: '1'},
            3: {period: '15.01', subs: '76', nonsubs: '141', profile: '365', main: '-', other: '1'},
            4: {period: '08.01', subs: '74', nonsubs: '141', profile: '363', main: '-', other: '1'},
            5: {period: '02.01', subs: '74', nonsubs: '141', profile: '362', main: '-', other: '1'},
            6: {period: '29.12', subs: '74', nonsubs: '143', profile: '366', main: '-', other: '1'},
            7: {period: '17.12', subs: '74', nonsubs: '143', profile: '365', main: '-', other: '1'}, 
            8: {period: '12.12', subs: '74', nonsubs: '143', profile: '364', main: '-', other: '1'}
        }
    },
    {id: 102, 
        src: require('../img/main/56.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '21%  ср  2:50',
        currStatistic: {
            1: {period: '30.01', subs: '67', nonsubs: '31', profile: '57', main: '60', other: '2'},
            2: {period: '24.01', subs: '66', nonsubs: '31', profile: '55', main: '60', other: '2'},
            3: {period: '15.01', subs: '65', nonsubs: '31', profile: '54', main: '60', other: '2'},
            4: {period: '08.01', subs: '63', nonsubs: '31', profile: '52', main: '60', other: '2'},
            5: {period: '02.01', subs: '62', nonsubs: '31', profile: '51', main: '60', other: '2'},
            6: {period: '29.12', subs: '62', nonsubs: '31', profile: '50', main: '60', other: '2'},
            7: {period: '17.12', subs: '62', nonsubs: '31', profile: '49', main: '60', other: '2'},
            8: {period: '12.12', subs: '62', nonsubs: '30', profile: '47', main: '60', other: '2'}
        }
    },
    {id: 103, src: '', w: '', h: ''},


    {id: 402, 
        src: require('../img/main/220.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '30.01', subs: '56', nonsubs: '2', profile: '7', main: '66', other: '1'},
            2: {period: '24.01', subs: '55', nonsubs: '1', profile: '5', main: '66', other: '1'},
            3: {period: '15.01', subs: '54', nonsubs: '1', profile: '4', main: '66', other: '1'},
            4: {period: '08.01', subs: '51', nonsubs: '1', profile: '2', main: '63', other: '1'},
            5: {period: '02.01', subs: '45', nonsubs: '1', profile: '1', main: '58', other: '1'}, 
            6: {period: '29.12', subs: '16', nonsubs: '0', profile: '-', main: '15', other: '1'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}, 
        }
    },
    {id: 403, 
        src: require('../img/main/219.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '30.01', subs: '49', nonsubs: '3', profile: '8', main: '55', other: '4'},
            2: {period: '24.01', subs: '48', nonsubs: '1', profile: '5', main: '55', other: '4'},
            3: {period: '15.01', subs: '47', nonsubs: '1', profile: '4', main: '55', other: '4'},
            4: {period: '08.01', subs: '46', nonsubs: '1', profile: '2', main: '55', other: '4'},
            5: {period: '02.01', subs: '45', nonsubs: '1', profile: '1', main: '55', other: '4'}, 
            6: {period: '29.12', subs: '38', nonsubs: '0', profile: '-', main: '45', other: '1'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}, 
        }
    },
    {id: 404, 
        src: require('../img/main/217.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '30.01', subs: '65', nonsubs: '33', profile: '18', main: '67', other: '27'},
            2: {period: '24.01', subs: '64', nonsubs: '32', profile: '15', main: '67', other: '27'}, 
            3: {period: '15.01', subs: '63', nonsubs: '32', profile: '14', main: '67', other: '26'},
            4: {period: '08.01', subs: '63', nonsubs: '31', profile: '11', main: '67', other: '26'},
            5: {period: '02.01', subs: '62', nonsubs: '31', profile: '10', main: '67', other: '26'},
            6: {period: '17.12-29.12', subs: '62', nonsubs: '30', profile: '9', main: '67', other: '26'},
            7: {period: '12.12', subs: '61', nonsubs: '28', profile: '7', main: '66', other: '26'}, 
            8: {period: '08.12', subs: '49', nonsubs: '25', profile: '1', main: '53', other: '26'}
        }
    },
    {id: 405, 
        src: require('../img/main/216.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '30.01', subs: '41', nonsubs: '17', profile: '26', main: '35', other: '2'},
            2: {period: '24.01', subs: '40', nonsubs: '16', profile: '24', main: '35', other: '2'},
            3: {period: '15.01', subs: '39', nonsubs: '16', profile: '23', main: '35', other: '2'}, 
            4: {period: '08.01', subs: '39', nonsubs: '15', profile: '20', main: '35', other: '2'},
            5: {period: '02.01', subs: '38', nonsubs: '15', profile: '19', main: '35', other: '2'},
            6: {period: '17.12-29.12', subs: '38', nonsubs: '14', profile: '18', main: '35', other: '2'},
            7: {period: '12.12', subs: '38', nonsubs: '12', profile: '16', main: '35', other: '2'},
            8: {period: '08.12', subs: '34', nonsubs: '8', profile: '10', main: '31', other: '2'}
        }
    },
    {id: 407, 
        src: require('../img/main/214.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '30.01', subs: '56', nonsubs: '19', profile: '28', main: '56', other: '1'},
            1: {period: '15.01-24.01', subs: '55', nonsubs: '19', profile: '27', main: '56', other: '1'},
            2: {period: '02.01-08.01', subs: '54', nonsubs: '19', profile: '25', main: '56', other: '1'}, 
            3: {period: '29.12', subs: '54', nonsubs: '18', profile: '24', main: '56', other: '1'},
            4: {period: '17.12', subs: '53', nonsubs: '18', profile: '24', main: '54', other: '1'},
            5: {period: '12.12', subs: '53', nonsubs: '16', profile: '21', main: '54', other: '1'},
            6: {period: '08.12', subs: '53', nonsubs: '14', profile: '17', main: '54', other: '1'},
            7: {period: '04.12', subs: '48', nonsubs: '6', profile: '7', main: '49', other: '1'}
        }
    },
    {id: 408, 
        src: require('../img/main/213.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --', 
        currStatistic: {
            1: {period: '15.01-30.01', subs: '54', nonsubs: '20', profile: '29', main: '57', other: '4'},
            2: {period: '02.01-08.01', subs: '54', nonsubs: '19', profile: '28', main: '57', other: '4'}, 
            3: {period: '17.12-29.12', subs: '54', nonsubs: '18', profile: '27', main: '57', other: '4'},
            4: {period: '12.12', subs: '54', nonsubs: '16', profile: '24', main: '57', other: '4'},
            5: {period: '08.12', subs: '54', nonsubs: '14', profile: '20', main: '57', other: '4'},
            6: {period: '04.12', subs: '51', nonsubs: '7', profile: '10', main: '55', other: '4'},
            7: {period: '02.12', subs: '49', nonsubs: '5', profile: '7', main: '53', other: '4'}, 
            8: {period: '28.11', subs: '28', nonsubs: '1', profile: '1', main: '28', other: '3'}
        }
    },
    {id: 411, 
        src: require('../img/main/80.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '50', nonsubs: '20', profile: '25', main: '48', other: '3'},
            2: {period: '15.01-24.01', subs: '50', nonsubs: '19', profile: '24', main: '48', other: '3'},
            3: {period: '02.01-08.01', subs: '50', nonsubs: '18', profile: '23', main: '48', other: '3'},
            4: {period: '17.12-29.12', subs: '50', nonsubs: '18', profile: '22', main: '48', other: '3'},
            5: {period: '12.12', subs: '50', nonsubs: '16', profile: '20', main: '48', other: '3'},
            6: {period: '08.12', subs: '50', nonsubs: '14', profile: '18', main: '48', other: '3'},
            7: {period: '04.12', subs: '50', nonsubs: '8', profile: '12', main: '48', other: '3'},
            8: {period: '02.12', subs: '49', nonsubs: '7', profile: '11', main: '47', other: '3'}
        }
    },
    {id: 414, 
        src: require('../img/main/77.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '48', nonsubs: '20', profile: '37', main: '47', other: '2'},
            2: {period: '15.01-24.01', subs: '48', nonsubs: '20', profile: '36', main: '47', other: '2'},
            3: {period: '08.01', subs: '47', nonsubs: '19', profile: '34', main: '47', other: '2'},
            4: {period: '02.01', subs: '47', nonsubs: '18', profile: '33', main: '47', other: '2'},
            5: {period: '12.12', subs: '47', nonsubs: '16', profile: '27', main: '47', other: '2'},
            6: {period: '08.12', subs: '47', nonsubs: '15', profile: '26', main: '47', other: '2'},
            7: {period: '04.12', subs: '45', nonsubs: '12', profile: '21', main: '47', other: '2'},
            8: {period: '02.12', subs: '45', nonsubs: '11', profile: '18', main: '47', other: '2'}
        }
    },
    {id: 417, 
        src: require('../img/main/74.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '35', nonsubs: '18', profile: '34', main: '37', other: '4'},
            1: {period: '24.01', subs: '35', nonsubs: '18', profile: '33', main: '37', other: '4'},
            2: {period: '15.01', subs: '35', nonsubs: '18', profile: '32', main: '37', other: '4'},
            3: {period: '08.01', subs: '34', nonsubs: '17', profile: '30', main: '37', other: '4'},
            4: {period: '02.01', subs: '34', nonsubs: '17', profile: '29', main: '37', other: '4'},
            5: {period: '12.12', subs: '34', nonsubs: '14', profile: '23', main: '37', other: '4'},
            6: {period: '08.12', subs: '34', nonsubs: '13', profile: '22', main: '37', other: '4'},
            7: {period: '04.12', subs: '34', nonsubs: '11', profile: '20', main: '37', other: '4'}
        }
    },
    {id: 418, 
        src: require('../img/main/72.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '40', nonsubs: '17', profile: '29', main: '42', other: '3'},
            2: {period: '08.01', subs: '39', nonsubs: '16', profile: '26', main: '42', other: '3'},
            3: {period: '02.01', subs: '39', nonsubs: '15', profile: '25', main: '42', other: '3'},
            4: {period: '08.12-12.12', subs: '39', nonsubs: '12', profile: '21', main: '42', other: '3'},
            5: {period: '04.12', subs: '39', nonsubs: '10', profile: '19', main: '42', other: '3'},
            6: {period: '02.12', subs: '39', nonsubs: '8', profile: '16', main: '42', other: '3'},
            7: {period: '28.11', subs: '39', nonsubs: '7', profile: '15', main: '42', other: '3'},
            8: {period: '20.11', subs: '39', nonsubs: '6', profile: '14', main: '42', other: '3'}
        }
    },

    {id: 419, 
        src: require('../img/main/71.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '58', nonsubs: '20', profile: '30', main: '64', other: '1'},
            2: {period: '02.01-08.01', subs: '57', nonsubs: '19', profile: '27', main: '64', other: '1'},
            3: {period: '12.12', subs: '57', nonsubs: '16', profile: '24', main: '64', other: '1'},
            4: {period: '08.12', subs: '57', nonsubs: '15', profile: '23', main: '64', other: '1'},
            5: {period: '04.12', subs: '57', nonsubs: '13', profile: '21', main: '64', other: '1'},
            6: {period: '02.12', subs: '57', nonsubs: '12', profile: '19', main: '64', other: '1'}, 
            7: {period: '28.11', subs: '57', nonsubs: '12', profile: '18', main: '64', other: '1'}, 
            8: {period: '20.11', subs: '57', nonsubs: '11', profile: '17', main: '64', other: '1'}
        }
    },
    {id: 420, 
        src: require('../img/main/70.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '58', nonsubs: '29', profile: '44', main: '60', other: '1'},
            2: {period: '15.01', subs: '58', nonsubs: '29', profile: '43', main: '60', other: '1'},
            3: {period: '02.01-08.01', subs: '57', nonsubs: '28', profile: '40', main: '60', other: '1'},
            4: {period: '12.12', subs: '57', nonsubs: '25', profile: '36', main: '59', other: '1'},
            5: {period: '08.12', subs: '57', nonsubs: '23', profile: '34', main: '59', other: '1'},
            6: {period: '04.12', subs: '57', nonsubs: '21', profile: '32', main: '59', other: '1'},
            7: {period: '02.12', subs: '57', nonsubs: '19', profile: '29', main: '59', other: '1'}, 
            8: {period: '28.11', subs: '57', nonsubs: '19', profile: '28', main: '59', other: '1'}
        }
    },
    {id: 422, 
        src: require('../img/main/68.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '56', nonsubs: '23', profile: '39', main: '59', other: '5'},
            2: {period: '15.01', subs: '56', nonsubs: '23', profile: '38', main: '59', other: '5'},
            3: {period: '02.01-08.01', subs: '55', nonsubs: '22', profile: '36', main: '59', other: '5'},
            4: {period: '12.12', subs: '55', nonsubs: '19', profile: '32', main: '59', other: '5'},
            5: {period: '08.12', subs: '55', nonsubs: '18', profile: '31', main: '59', other: '5'},
            6: {period: '04.12', subs: '55', nonsubs: '15', profile: '27', main: '59', other: '5'}, 
            7: {period: '02.12', subs: '55', nonsubs: '13', profile: '24', main: '59', other: '5'}, 
            8: {period: '20-28.11', subs: '55', nonsubs: '13', profile: '23', main: '59', other: '5'}
        }
    },
    {id: 423, 
        src: require('../img/main/67.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '109', nonsubs: '23', profile: '37', main: '117', other: '4'},
            2: {period: '15.01', subs: '109', nonsubs: '23', profile: '36', main: '117', other: '4'},
            3: {period: '02.01-08.01', subs: '108', nonsubs: '23', profile: '35', main: '117', other: '4'},
            4: {period: '12.12', subs: '108', nonsubs: '20', profile: '31', main: '117', other: '4'},
            5: {period: '08.12', subs: '108', nonsubs: '19', profile: '30', main: '117', other: '4'},
            6: {period: '04.12', subs: '108', nonsubs: '15', profile: '25', main: '117', other: '4'},
            7: {period: '02.12', subs: '108', nonsubs: '14', profile: '24', main: '117', other: '4'},
            8: {period: '20-28.11', subs: '108', nonsubs: '14', profile: '23', main: '117', other: '4'}
        }
    },
    {id: 424, 
        src: require('../img/main/66.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '31%  чт 6:10',
        currStatistic: {
            1: {period: '30.01', subs: '44', nonsubs: '19', profile: '31', main: '42', other: '1'},
            2: {period: '15.01-24.01', subs: '44', nonsubs: '19', profile: '30', main: '42', other: '1'},
            3: {period: '02.01-08.01', subs: '43', nonsubs: '19', profile: '29', main: '42', other: '1'},
            4: {period: '08.12', subs: '43', nonsubs: '18', profile: '26', main: '42', other: '1'}, 
            5: {period: '02.12-04.12', subs: '43', nonsubs: '14', profile: '21', main: '42', other: '1'}, 
            6: {period: '20-28.11', subs: '43', nonsubs: '14', profile: '20', main: '42', other: '1'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}, 
        }
    },
    {id: 425, 
        src: require('../img/main/64.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '28%  вс 7:01',
        currStatistic: {
            1: {period: '30.01', subs: '53', nonsubs: '18', profile: '34', main: '47', other: '3'},
            2: {period: '15.01-24.01', subs: '53', nonsubs: '18', profile: '33', main: '47', other: '3'},
            3: {period: '08.01', subs: '52', nonsubs: '18', profile: '32', main: '47', other: '3'},
            4: {period: '02.01', subs: '52', nonsubs: '18', profile: '31', main: '47', other: '3'},
            5: {period: '08.12', subs: '52', nonsubs: '16', profile: '28', main: '47', other: '3'}, 
            6: {period: '02.12-04.12', subs: '52', nonsubs: '13', profile: '25', main: '47', other: '3'}, 
            7: {period: '20-28.11', subs: '52', nonsubs: '13', profile: '24', main: '47', other: '3'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}
        }
    },
    {id: 428, 
        src: require('../img/main/59.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '24%  ср  2:15',
        currStatistic: {
            1: {period: '30.01', subs: '68', nonsubs: '16', profile: '25', main: '65', other: '2'},
            2: {period: '15.01-24.01', subs: '68', nonsubs: '15', profile: '24', main: '65', other: '2'},
            3: {period: '08.01', subs: '67', nonsubs: '15', profile: '23', main: '65', other: '2'},
            4: {period: '02.01', subs: '67', nonsubs: '14', profile: '22', main: '65', other: '2'},
            5: {period: '08.12', subs: '67', nonsubs: '13', profile: '21', main: '65', other: '2'}, 
            6: {period: '02.12-04.12', subs: '66', nonsubs: '9', profile: '16', main: '65', other: '2'}, 
            7: {period: '20-28.11', subs: '66', nonsubs: '9', profile: '15', main: '65', other: '2'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 429, 
        src: require('../img/main/58.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '19%  пн  3:40',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '56', nonsubs: '19', profile: '30', main: '53', other: '2'},
            2: {period: '08.01', subs: '55', nonsubs: '19', profile: '29', main: '53', other: '2'},
            3: {period: '02.01', subs: '55', nonsubs: '18', profile: '28', main: '53', other: '2'},
            4: {period: '08.12', subs: '55', nonsubs: '17', profile: '27', main: '53', other: '2'},
            5: {period: '04.12', subs: '53', nonsubs: '13', profile: '21', main: '53', other: '2'}, 
            6: {period: '02.12', subs: '53', nonsubs: '12', profile: '20', main: '53', other: '2'}, 
            7: {period: '20-28.11', subs: '53', nonsubs: '12', profile: '19', main: '53', other: '2'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 432, 
        src: require('../img/main/54.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '13%  чт  5:25',
        currStatistic: {
            1: {period: '30.01', subs: '49', nonsubs: '22', profile: '34', main: '45', other: '3'},
            2: {period: '15.01-24.01', subs: '49', nonsubs: '20', profile: '32', main: '45', other: '3'},
            3: {period: '02.01-08.01', subs: '48', nonsubs: '19', profile: '30', main: '45', other: '3'},
            4: {period: '08.12', subs: '48', nonsubs: '17', profile: '28', main: '45', other: '3'}, 
            5: {period: '02.12-04.12', subs: '48', nonsubs: '14', profile: '25', main: '45', other: '3'}, 
            6: {period: '20-28.11', subs: '48', nonsubs: '14', profile: '24', main: '45', other: '3'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 436, 
        src: require('../img/main/50.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '29%  сб  3:10',
        currStatistic: {
            1: {period: '30.01', subs: '56', nonsubs: '35', profile: '57', main: '50', other: '3'},
            2: {period: '15.01-24.01', subs: '56', nonsubs: '34', profile: '55', main: '50', other: '3'},
            3: {period: '02.01-08.01', subs: '55', nonsubs: '33', profile: '53', main: '50', other: '3'},
            4: {period: '08.12', subs: '55', nonsubs: '33', profile: '50', main: '50', other: '3'},
            5: {period: '04.12', subs: '54', nonsubs: '30', profile: '46', main: '50', other: '3'},
            6: {period: '02.12', subs: '54', nonsubs: '29', profile: '45', main: '50', other: '3'}, 
            7: {period: '28.11', subs: '54', nonsubs: '29', profile: '44', main: '50', other: '3'}, 
            8: {period: '20.11', subs: '54', nonsubs: '28', profile: '42', main: '50', other: '3'}
        }
    },
    {id: 437, 
        src: require('../img/main/49.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '27%  пт  3:05',
        currStatistic: {
            1: {period: '30.01', subs: '49', nonsubs: '25', profile: '44', main: '44', other: '6'},
            2: {period: '15.01-24.01', subs: '49', nonsubs: '23', profile: '42', main: '44', other: '6'},
            3: {period: '02.01-08.01', subs: '48', nonsubs: '22', profile: '40', main: '44', other: '6'},
            4: {period: '08.12', subs: '48', nonsubs: '22', profile: '39', main: '44', other: '6'},
            5: {period: '02.12-04.12', subs: '48', nonsubs: '19', profile: '36', main: '44', other: '6'}, 
            6: {period: '28.11', subs: '48', nonsubs: '19', profile: '35', main: '44', other: '6'}, 
            7: {period: '20.11', subs: '48', nonsubs: '19', profile: '34', main: '44', other: '6'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 438, 
        src: require('../img/main/48.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '27%  ср  6:31',
        currStatistic: {
            1: {period: '30.01', subs: '51', nonsubs: '27', profile: '45', main: '51', other: '-'},
            2: {period: '15.01-24.01', subs: '51', nonsubs: '26', profile: '44', main: '51', other: '-'},
            3: {period: '02.01-08.01', subs: '50', nonsubs: '26', profile: '43', main: '51', other: '-'},
            4: {period: '08.12', subs: '50', nonsubs: '25', profile: '41', main: '51', other: '-'},
            5: {period: '04.12', subs: '51', nonsubs: '21', profile: '37', main: '51', other: '-'}, 
            6: {period: '02.12', subs: '51', nonsubs: '20', profile: '36', main: '51', other: '-'}, 
            7: {period: '20-28.11', subs: '51', nonsubs: '20', profile: '35', main: '51', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 439, 
        src: require('../img/main/47.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '30%  сб  7:27',
        currStatistic: {
            1: {period: '30.01', subs: '51', nonsubs: '25', profile: '42', main: '52', other: '7'},
            2: {period: '24.01', subs: '51', nonsubs: '24', profile: '41', main: '52', other: '7'},
            3: {period: '15.01', subs: '51', nonsubs: '24', profile: '41', main: '52', other: '6'},
            4: {period: '08.01', subs: '50', nonsubs: '24', profile: '39', main: '52', other: '6'},
            5: {period: '02.01', subs: '50', nonsubs: '24', profile: '39', main: '52', other: '5'},
            6: {period: '08.12', subs: '50', nonsubs: '21', profile: '35', main: '52', other: '4'},
            7: {period: '04.12', subs: '51', nonsubs: '16', profile: '30', main: '52', other: '4'},
            8: {period: '02.12', subs: '51', nonsubs: '15', profile: '28', main: '52', other: '4'}
        }
    },
    {id: 441, 
        src: require('../img/main/44.jpg'), 
        w: '', 
        h: '', 
        text: '', tags: '', 
        engagement: '22%  пн  2:40',
        currStatistic: {
            1: {period: '30.01', subs: '45', nonsubs: '21', profile: '42', main: '45', other: '1'},
            2: {period: '15.01-24.01', subs: '45', nonsubs: '21', profile: '41', main: '45', other: '1'},
            3: {period: '02.01-08.01', subs: '44', nonsubs: '20', profile: '38', main: '45', other: '1'},
            4: {period: '08.12', subs: '44', nonsubs: '18', profile: '34', main: '45', other: '1'},
            5: {period: '02.12-04.12', subs: '44', nonsubs: '15', profile: '30', main: '45', other: '1'}, 
            6: {period: '28.11', subs: '44', nonsubs: '15', profile: '29', main: '45', other: '1'}, 
            7: {period: '20.11', subs: '44', nonsubs: '14', profile: '27', main: '45', other: '1'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 442, 
        src: require('../img/main/43.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '29%  вс  5:05',
        currStatistic: {
            1: {period: '30.01', subs: '37', nonsubs: '18', profile: '39', main: '33', other: '-'},
            2: {period: '24.01', subs: '37', nonsubs: '18', profile: '38', main: '33', other: '-'},
            3: {period: '15.01', subs: '37', nonsubs: '18', profile: '37', main: '33', other: '-'},
            4: {period: '02.01-08.01', subs: '36', nonsubs: '17', profile: '34', main: '33', other: '-'},
            5: {period: '08.12', subs: '36', nonsubs: '17', profile: '33', main: '33', other: '-'},
            6: {period: '04.12', subs: '37', nonsubs: '14', profile: '30', main: '33', other: '-'}, 
            7: {period: '28.11-02.12', subs: '37', nonsubs: '13', profile: '28', main: '33', other: '-'}, 
            8: {period: '20.11', subs: '37', nonsubs: '13', profile: '27', main: '33', other: '-'}
        }
    },
    {id: 443, 
        src: require('../img/main/34.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '26%  ср  3:15',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '63', nonsubs: '21', profile: '47', main: '84', other: '5'},
            2: {period: '15.01', subs: '63', nonsubs: '21', profile: '46', main: '84', other: '5'},
            3: {period: '08.12-08.01', subs: '62', nonsubs: '21', profile: '45', main: '84', other: '5'},
            4: {period: '04.12', subs: '63', nonsubs: '18', profile: '42', main: '84', other: '5'}, 
            5: {period: '28.11-02.12', subs: '63', nonsubs: '17', profile: '39', main: '84', other: '5'}, 
            6: {period: '20.11', subs: '63', nonsubs: '16', profile: '38', main: '84', other: '5'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 445, 
        src: require('../img/main/33.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '29%  вт  5:26',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '72', nonsubs: '30', profile: '58', main: '75', other: '11'},
            2: {period: '15.01', subs: '71', nonsubs: '30', profile: '56', main: '75', other: '11'},
            3: {period: '08.12-08.01', subs: '70', nonsubs: '30', profile: '55', main: '75', other: '11'}, 
            4: {period: '04.12', subs: '71', nonsubs: '27', profile: '52', main: '75', other: '11'}, 
            5: {period: '20.11-02.12', subs: '71', nonsubs: '27', profile: '49', main: '75', other: '11'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 446, 
        src: require('../img/main/30.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '',
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '72', nonsubs: '37', profile: '61', main: '70', other: '23'},
            2: {period: '08.12-08.01', subs: '71', nonsubs: '37', profile: '60', main: '70', other: '23'}, 
            3: {period: '04.12', subs: '72', nonsubs: '35', profile: '57', main: '70', other: '23'}, 
            4: {period: '20.11-02.12', subs: '72', nonsubs: '35', profile: '54', main: '70', other: '23'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 447, 
        src: require('../img/main/31.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '26%  вс  2:45',
        currStatistic: {
            1: {period: '30.01', subs: '97', nonsubs: '44', profile: '78', main: '101', other: '25'},
            2: {period: '24.01', subs: '97', nonsubs: '44', profile: '77', main: '101', other: '25'},
            3: {period: '15.01', subs: '96', nonsubs: '44', profile: '76', main: '101', other: '25'},
            4: {period: '02.01-08.01', subs: '95', nonsubs: '44', profile: '74', main: '101', other: '25'},
            5: {period: '08.12', subs: '95', nonsubs: '44', profile: '73', main: '101', other: '25'}, 
            6: {period: '04.12', subs: '95', nonsubs: '43', profile: '70', main: '101', other: '25'}, 
            7: {period: '20.11-02.12', subs: '95', nonsubs: '43', profile: '67', main: '101', other: '25'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 448, 
        src: require('../img/main/27.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  пт  8:40',
        currStatistic: {
            1: {period: '30.01', subs: '57', nonsubs: '37', profile: '93', main: '38', other: '4'},
            2: {period: '24.01', subs: '57', nonsubs: '37', profile: '92', main: '38', other: '4'},
            3: {period: '15.01', subs: '56', nonsubs: '37', profile: '91', main: '38', other: '4'},
            4: {period: '02.01-08.01', subs: '54', nonsubs: '37', profile: '88', main: '38', other: '4'},
            5: {period: '08.12', subs: '54', nonsubs: '37', profile: '87', main: '38', other: '3'},
            6: {period: '04.12', subs: '55', nonsubs: '35', profile: '84', main: '38', other: '3'}, 
            7: {period: '02.12', subs: '55', nonsubs: '35', profile: '81', main: '38', other: '3'}, 
            8: {period: '20-28.11', subs: '55', nonsubs: '34', profile: '79', main: '38', other: '3'}
        }
    },

    {id: 449, 
        src: require('../img/main/29.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '20%  чт  8:40',
        currStatistic: {
            1: {period: '30.01', subs: '77', nonsubs: '32', profile: '77', main: '61', other: '2'},
            2: {period: '15.01-24.01', subs: '77', nonsubs: '32', profile: '76', main: '61', other: '2'},
            3: {period: '02.01-08.01', subs: '76', nonsubs: '30', profile: '72', main: '61', other: '2'}, 
            4: {period: '08.12', subs: '76', nonsubs: '30', profile: '71', main: '61', other: '2'}, 
            5: {period: '20.11-04.12', subs: '75', nonsubs: '29', profile: '68', main: '61', other: '2'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 450, 
        src: require('../img/main/26.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '22%  чт  1:15',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '54', nonsubs: '29', profile: '64', main: '36', other: '1'}, 
            2: {period: '08.12-08.01', subs: '54', nonsubs: '27', profile: '62', main: '36', other: '1'}, 
            3: {period: '20.11-04.12', subs: '54', nonsubs: '26', profile: '60', main: '36', other: '1'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 451, 
        src: require('../img/main/28.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '22%  ср  2:50',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '55', nonsubs: '30', profile: '72', main: '36', other: '1'},
            2: {period: '15.01', subs: '55', nonsubs: '30', profile: '71', main: '36', other: '1'},
            3: {period: '08.12-08.01', subs: '54', nonsubs: '29', profile: '69', main: '36', other: '1'}, 
            4: {period: '04.12', subs: '54', nonsubs: '27', profile: '66', main: '36', other: '1'}, 
            5: {period: '20.11-02.12', subs: '54', nonsubs: '26', profile: '64', main: '36', other: '1'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 452, 
        src: require('../img/main/23.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '20%  вт  3:15',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '65', nonsubs: '31', profile: '73', main: '63', other: '-'},
            2: {period: '15.01', subs: '65', nonsubs: '31', profile: '72', main: '63', other: '-'},
            3: {period: '08.12-08.01', subs: '64', nonsubs: '31', profile: '71', main: '63', other: '-'}, 
            4: {period: '04.12', subs: '64', nonsubs: '29', profile: '68', main: '63', other: '-'}, 
            5: {period: '20.11-02.12', subs: '64', nonsubs: '28', profile: '66', main: '63', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 453, 
        src: require('../img/main/20.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '60', nonsubs: '32', profile: '82', main: '35', other: '5'},
            2: {period: '15.01', subs: '60', nonsubs: '32', profile: '81', main: '35', other: '5'},
            3: {period: '08.12-08.01', subs: '59', nonsubs: '32', profile: '80', main: '35', other: '5'}, 
            4: {period: '04.12', subs: '59', nonsubs: '30', profile: '77', main: '35', other: '5'}, 
            5: {period: '20.11-02.12', subs: '59', nonsubs: '30', profile: '75', main: '35', other: '5'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 454, 
        src: require('../img/main/21.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  пн  3:20',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '70', nonsubs: '25', profile: '64', main: '52', other: '1'}, 
            2: {period: '08.12-08.01', subs: '69', nonsubs: '25', profile: '63', main: '52', other: '1'}, 
            3: {period: '20.11-04.12', subs: '69', nonsubs: '23', profile: '60', main: '52', other: '1'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 455, 
        src: require('../img/main/18.jpg'), 
        w: '', 
        h: '', 
        tags: '', 
        engagement: '31%  сб  11:19',
        currStatistic: {
            1: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            2: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            3: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            4: {period: '30.01', subs: '74', nonsubs: '24', profile: '68', main: '59', other: '5'},
            5: {period: '15.01-24.01', subs: '74', nonsubs: '23', profile: '67', main: '59', other: '5'},
            6: {period: '08.12-08.01', subs: '73', nonsubs: '23', profile: '65', main: '59', other: '5'}, 
            7: {period: '04.12', subs: '73', nonsubs: '21', profile: '60', main: '59', other: '5'}, 
            8: {period: '20.11-02.12', subs: '73', nonsubs: '20', profile: '59', main: '59', other: '5'}
        }
    },
    {id: 457, 
        src: require('../img/main/7.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '30.01', subs: '91', nonsubs: '49', profile: '127', main: '88', other: '3'},
            2: {period: '15.01-24.01', subs: '91', nonsubs: '49', profile: '126', main: '88', other: '3'},
            3: {period: '02.01-08.01', subs: '90', nonsubs: '49', profile: '124', main: '88', other: '3'},
            4: {period: '08.12', subs: '90', nonsubs: '49', profile: '123', main: '88', other: '1'},
            5: {period: '04.12', subs: '90', nonsubs: '47', profile: '118', main: '88', other: '1'}, 
            6: {period: '02.12', subs: '90', nonsubs: '45', profile: '116', main: '88', other: '1'}, 
            7: {period: '20-28.11', subs: '90', nonsubs: '44', profile: '114', main: '88', other: '1'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 458, 
        src: require('../img/main/8.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '25%  вт  4:10',
        currStatistic: {
            1: {period: '30.01', subs: '77', nonsubs: '46', profile: '124', main: '59', other: '1'},
            2: {period: '15.01-24.01', subs: '77', nonsubs: '46', profile: '123', main: '59', other: '1'},
            3: {period: '02.01-08.01', subs: '75', nonsubs: '46', profile: '120', main: '59', other: '1'},
            4: {period: '04.12', subs: '75', nonsubs: '46', profile: '118', main: '59', other: '1'},
            5: {period: '20.11-02.12', subs: '75', nonsubs: '44', profile: '113', main: '59', other: '1'}, 
            6: {period: '14.11', subs: '75', nonsubs: '44', profile: '111', main: '59', other: '1'}, 
            7: {period: '7.11', subs: '75', nonsubs: '44', profile: '111', main: '59', other: '1'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 461, 
        src: require('../img/main/5.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '87', nonsubs: '53', profile: '116', main: '81', other: '9'},
            2: {period: '02.01-08.01', subs: '86', nonsubs: '52', profile: '114', main: '81', other: '9'},
            3: {period: '08.12', subs: '86', nonsubs: '51', profile: '112', main: '81', other: '9'},
            4: {period: '04.12', subs: '86', nonsubs: '49', profile: '110', main: '81', other: '9'},
            5: {period: '28.11-02.12', subs: '86', nonsubs: '48', profile: '108', main: '81', other: '9'},
            6: {period: '20.11', subs: '86', nonsubs: '48', profile: '107', main: '81', other: '9'}, 
            7: {period: '14.11', subs: '86', nonsubs: '48', profile: '106', main: '81', other: '9'}, 
            8: {period: '7.11', subs: '86', nonsubs: '48', profile: '106', main: '81', other: '9'}
        }
    },
    {id: 462, 
        src: require('../img/main/11.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '--  --  --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '89', nonsubs: '58', profile: '130', main: '75', other: '11'},
            2: {period: '02.01-08.01', subs: '88', nonsubs: '57', profile: '128', main: '75', other: '11'},
            3: {period: '08.12', subs: '88', nonsubs: '56', profile: '126', main: '75', other: '11'},
            4: {period: '04.12', subs: '88', nonsubs: '55', profile: '125', main: '75', other: '11'}, 
            5: {period: '28.11-02.12', subs: '88', nonsubs: '54', profile: '123', main: '75', other: '11'}, 
            6: {period: '20.11', subs: '88', nonsubs: '54', profile: '122', main: '75', other: '11'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 465, 
        src: require('../img/main/12.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '24%  чт  8:10',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '104', nonsubs: '94', profile: '199', main: '95', other: '25'},
            2: {period: '02.01-08.01', subs: '103', nonsubs: '94', profile: '198', main: '95', other: '25'},
            3: {period: '08.12', subs: '103', nonsubs: '93', profile: '192', main: '95', other: '25'},
            4: {period: '04.12', subs: '103', nonsubs: '91', profile: '190', main: '95', other: '25'},
            5: {period: '02.12', subs: '103', nonsubs: '90', profile: '186', main: '95', other: '25'}, 
            6: {period: '28.11', subs: '103', nonsubs: '90', profile: '186', main: '95', other: '24'}, 
            7: {period: '20.11', subs: '103', nonsubs: '90', profile: '184', main: '95', other: '24'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 466, 
        src: require('../img/main/13.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '25%  ср  3:17',
        currStatistic: {
            1: {period: '30.01', subs: '108', nonsubs: '78', profile: '184', main: '88', other: '6'},
            2: {period: '15.01-24.01', subs: '108', nonsubs: '77', profile: '183', main: '88', other: '6'},
            3: {period: '02.01-08.01', subs: '106', nonsubs: '77', profile: '181', main: '88', other: '6'},
            4: {period: '08.12', subs: '106', nonsubs: '75', profile: '176', main: '88', other: '6'},
            5: {period: '04.12', subs: '106', nonsubs: '73', profile: '174', main: '88', other: '6'}, 
            6: {period: '28.11-02.12', subs: '106', nonsubs: '73', profile: '172', main: '88', other: '6'}, 
            7: {period: '20.11', subs: '106', nonsubs: '73', profile: '171', main: '88', other: '6'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 467, 
        src: require('../img/main/3.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '121', nonsubs: '122', profile: '393', main: '88', other: '13'},
            2: {period: '15.01-24.01', subs: '121', nonsubs: '121', profile: '392', main: '88', other: '13'},
            3: {period: '02.01-08.01', subs: '121', nonsubs: '120', profile: '390', main: '88', other: '13'},
            4: {period: '08.12', subs: '121', nonsubs: '116', profile: '382', main: '88', other: '13'},
            5: {period: '02.12', subs: '119', nonsubs: '111', profile: '369', main: '88', other: '13'},
            6: {period: '28.11', subs: '119', nonsubs: '110', profile: '365', main: '88', other: '13'}, 
            7: {period: '14.11', subs: '119', nonsubs: '110', profile: '363', main: '88', other: '13'}, 
            8: {period: '7.11', subs: '119', nonsubs: '110', profile: '361', main: '88', other: '13'}
        }
    },
    {id: 468, 
        src: require('../img/main/15.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '15%  вт  11:26',
        currStatistic: {
            1: {period: '30.01', subs: '94', nonsubs: '149', profile: '305', main: '47', other: '20'},
            2: {period: '15.01-24.01', subs: '94', nonsubs: '148', profile: '304', main: '47', other: '20'},
            3: {period: '02.01-08.01', subs: '93', nonsubs: '147', profile: '302', main: '47', other: '20'},
            4: {period: '08.12', subs: '93', nonsubs: '146', profile: '296', main: '47', other: '20'},
            5: {period: '04.12', subs: '93', nonsubs: '144', profile: '294', main: '47', other: '20'}, 
            6: {period: '28.11-02.12', subs: '93', nonsubs: '143', profile: '292', main: '47', other: '20'}, 
            7: {period: '20.11', subs: '93', nonsubs: '142', profile: '291', main: '47', other: '20'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 469, 
        src: require('../img/main/17.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '16%  чт  12:01',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '82', nonsubs: '140', profile: '315', main: '41', other: '10'},
            2: {period: '02.01-08.01', subs: '81', nonsubs: '140', profile: '313', main: '41', other: '10'},
            3: {period: '08.12', subs: '81', nonsubs: '139', profile: '307', main: '41', other: '10'},
            4: {period: '04.12', subs: '80', nonsubs: '138', profile: '305', main: '41', other: '10'}, 
            5: {period: '28.11-02.12', subs: '80', nonsubs: '138', profile: '304', main: '41', other: '10'}, 
            6: {period: '20.11', subs: '80', nonsubs: '137', profile: '302', main: '41', other: '10'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },

    {id: 470, 
        src: require('../img/main/221.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '83', nonsubs: '96', profile: '194', main: '74', other: '4'}, 
            2: {period: '02.01-08.01', subs: '82', nonsubs: '96', profile: '192', main: '74', other: '4'},
            3: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}, 
        }
    },


    {id: 471, 
        src: require('../img/main/182.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '71', nonsubs: '97', profile: '178', main: '59', other: '5'},
            2: {period: '02.01-08.01', subs: '70', nonsubs: '97', profile: '177', main: '59', other: '5'},
            3: {period: '08.12', subs: '70', nonsubs: '95', profile: '171', main: '59', other: '5'},
            4: {period: '04.12', subs: '70', nonsubs: '93', profile: '169', main: '59', other: '5'}, 
            5: {period: '28.11-02.12', subs: '70', nonsubs: '92', profile: '167', main: '59', other: '5'}, 
            6: {period: '23.11', subs: '70', nonsubs: '92', profile: '166', main: '59', other: '5'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 472, 
        src: require('../img/main/183.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '89', nonsubs: '120', profile: '231', main: '67', other: '4'},
            2: {period: '02.01-08.01', subs: '87', nonsubs: '120', profile: '229', main: '67', other: '4'},
            3: {period: '08.12', subs: '87', nonsubs: '117', profile: '222', main: '67', other: '4'},
            4: {period: '04.12', subs: '87', nonsubs: '115', profile: '220', main: '67', other: '4'}, 
            5: {period: '28.11-02.12', subs: '87', nonsubs: '114', profile: '218', main: '67', other: '4'}, 
            6: {period: '23.11', subs: '87', nonsubs: '114', profile: '217', main: '67', other: '4'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 473, 
        src: require('../img/main/184.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '103', nonsubs: '113', profile: '251', main: '99', other: '3'},
            2: {period: '02.01-08.01', subs: '102', nonsubs: '113', profile: '249', main: '99', other: '3'},
            3: {period: '08.12', subs: '102', nonsubs: '110', profile: '241', main: '99', other: '3'},
            4: {period: '04.12', subs: '102', nonsubs: '108', profile: '239', main: '99', other: '3'}, 
            5: {period: '28.11-02.12', subs: '102', nonsubs: '107', profile: '237', main: '99', other: '3'}, 
            6: {period: '23.11', subs: '102', nonsubs: '107', profile: '236', main: '99', other: '3'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    ///////
    {id: 474, 
        src: require('../img/main/185.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '100', nonsubs: '124', profile: '292', main: '156', other: '2'},
            2: {period: '02.01-08.01', subs: '99', nonsubs: '124', profile: '291', main: '156', other: '2'},
            3: {period: '08.21', subs: '99', nonsubs: '122', profile: '284', main: '156', other: '2'},
            4: {period: '04.12', subs: '99', nonsubs: '121', profile: '283', main: '156', other: '2'}, 
            5: {period: '28.11-02.12', subs: '99', nonsubs: '119', profile: '280', main: '156', other: '2'}, 
            6: {period: '23.11', subs: '99', nonsubs: '119', profile: '279', main: '156', other: '2'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 475, 
        src: require('../img/main/186.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '96', nonsubs: '129', profile: '279', main: '98', other: '16'},
            2: {period: '15.01', subs: '95', nonsubs: '128', profile: '277', main: '98', other: '16'},
            3: {period: '02.01-08.01', subs: '94', nonsubs: '128', profile: '276', main: '98', other: '16'},
            4: {period: '08.12', subs: '94', nonsubs: '126', profile: '270', main: '98', other: '16'},
            5: {period: '04.12', subs: '94', nonsubs: '125', profile: '269', main: '98', other: '16'}, 
            6: {period: '28.11-02.12', subs: '94', nonsubs: '124', profile: '266', main: '98', other: '16'}, 
            7: {period: '23.11', subs: '94', nonsubs: '123', profile: '264', main: '98', other: '16'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 476, 
        src: require('../img/main/187.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '24.01-30.01', subs: '83', nonsubs: '238', profile: '257', main: '40', other: '9'},
            2: {period: '15.01', subs: '82', nonsubs: '237', profile: '255', main: '40', other: '9'},
            3: {period: '02.01-08.01', subs: '80', nonsubs: '237', profile: '254', main: '40', other: '9'},
            4: {period: '08.12', subs: '81', nonsubs: '235', profile: '248', main: '40', other: '9'},
            5: {period: '04.12', subs: '81', nonsubs: '234', profile: '247', main: '40', other: '9'}, 
            6: {period: '28.11-02.12', subs: '81', nonsubs: '233', profile: '246', main: '40', other: '9'}, 
            7: {period: '23.11', subs: '81', nonsubs: '232', profile: '245', main: '40', other: '9'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}
        }
    },
    {id: 477, 
        src: require('../img/main/188.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '83', nonsubs: '267', profile: '210', main: '43', other: '7'},
            2: {period: '02.01-08.01', subs: '82', nonsubs: '267', profile: '209', main: '43', other: '7'},
            3: {period: '08.12', subs: '83', nonsubs: '265', profile: '206', main: '43', other: '7'},
            4: {period: '04.21', subs: '83', nonsubs: '264', profile: '205', main: '43', other: '7'}, 
            5: {period: '02.12', subs: '82', nonsubs: '264', profile: '204', main: '43', other: '7'}, 
            6: {period: '23-28.11', subs: '81', nonsubs: '263', profile: '203', main: '43', other: '7'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'}
        }
    },
    {id: 478, 
        src: require('../img/main/189.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '66', nonsubs: '118', profile: '266', main: '-', other: '2'},
            2: {period: '08.01', subs: '65', nonsubs: '118', profile: '265', main: '-', other: '2'}, 
            3: {period: '02.01', subs: '66', nonsubs: '123', profile: '275', main: '5', other: '1'}, 
            4: {period: '08.12', subs: '66', nonsubs: '121', profile: '272', main: '5', other: '1'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 479, 
        src: require('../img/main/190.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '56', nonsubs: '82', profile: '175', main: '-', other: '3'},
            2: {period: '08.01', subs: '55', nonsubs: '82', profile: '174', main: '-', other: '3'}, 
            3: {period: '02.01', subs: '57', nonsubs: '84', profile: '180', main: '-', other: '3'}, 
            4: {period: '08.12', subs: '57', nonsubs: '83', profile: '179', main: '-', other: '3'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 480, 
        src: require('../img/main/191.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '55', nonsubs: '77', profile: '167', main: '-', other: '1'},
            2: {period: '08.01', subs: '54', nonsubs: '77', profile: '166', main: '-', other: '1'}, 
            3: {period: '02.01', subs: '57', nonsubs: '79', profile: '172', main: '-', other: '1'}, 
            4: {period: '08.12', subs: '57', nonsubs: '78', profile: '171', main: '-', other: '1'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 481, 
        src: require('../img/main/192.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '30', nonsubs: '53', profile: '108', main: '-', other: '-'},
            2: {period: '08.01', subs: '29', nonsubs: '53', profile: '107', main: '-', other: '-'}, 
            3: {period: '02.01', subs: '30', nonsubs: '60', profile: '115', main: '-', other: '-'}, 
            4: {period: '08.12', subs: '30', nonsubs: '57', profile: '112', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 482, 
        src: require('../img/main/193.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '42', nonsubs: '73', profile: '146', main: '-', other: '1'},
            2: {period: '08.01', subs: '41', nonsubs: '73', profile: '145', main: '-', other: '1'}, 
            3: {period: '02.01', subs: '42', nonsubs: '79', profile: '153', main: '-', other: '1'}, 
            4: {period: '08.12', subs: '42', nonsubs: '76', profile: '150', main: '-', other: '1'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 483, 
        src: require('../img/main/194.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '41', nonsubs: '89', profile: '159', main: '-', other: '5'},
            2: {period: '15.01-24.01', subs: '41', nonsubs: '89', profile: '158', main: '-', other: '5'},
            3: {period: '08.01', subs: '40', nonsubs: '89', profile: '157', main: '-', other: '5'}, 
            4: {period: '02.01', subs: '40', nonsubs: '94', profile: '166', main: '-', other: '6'}, 
            5: {period: '08.12', subs: '40', nonsubs: '93', profile: '163', main: '-', other: '6'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 484, 
        src: require('../img/main/195.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '33', nonsubs: '95', profile: '189', main: '-', other: '2'},
            2: {period: '15.01-24.01', subs: '33', nonsubs: '94', profile: '188', main: '-', other: '2'},
            3: {period: '08.01', subs: '32', nonsubs: '94', profile: '186', main: '-', other: '2'}, 
            4: {period: '02.01', subs: '32', nonsubs: '102', profile: '197', main: '-', other: '2'}, 
            5: {period: '08.12', subs: '32', nonsubs: '99', profile: '192', main: '-', other: '2'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 485, 
        src: require('../img/main/196.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '47', nonsubs: '88', profile: '201', main: '-', other: '-'},
            2: {period: '15.01-24.01', subs: '47', nonsubs: '87', profile: '200', main: '-', other: '-'},
            3: {period: '08.01', subs: '46', nonsubs: '87', profile: '199', main: '-', other: '-'}, 
            4: {period: '02.01', subs: '46', nonsubs: '88', profile: '201', main: '-', other: '-'}, 
            5: {period: '08.12', subs: '46', nonsubs: '87', profile: '199', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 486, 
        src: require('../img/main/197.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '33', nonsubs: '37', profile: '84', main: '-', other: '2'}, 
            2: {period: '08.01', subs: '32', nonsubs: '37', profile: '83', main: '-', other: '2'}, 
            3: {period: '08.12-02.01', subs: '32', nonsubs: '40', profile: '86', main: '-', other: '2'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 487, 
        src: require('../img/main/198.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '32', nonsubs: '32', profile: '79', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '31', nonsubs: '32', profile: '78', main: '-', other: '-'}, 
            3: {period: '08.12-02.01', subs: '31', nonsubs: '34', profile: '80', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 488, 
        src: require('../img/main/199.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '30', nonsubs: '36', profile: '90', main: '-', other: '3'}, 
            2: {period: '08.01', subs: '29', nonsubs: '36', profile: '89', main: '-', other: '3'}, 
            3: {period: '08.12-02.01', subs: '29', nonsubs: '39', profile: '92', main: '-', other: '3'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 489, 
        src: require('../img/main/200.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '29', nonsubs: '26', profile: '77', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '28', nonsubs: '26', profile: '76', main: '-', other: '-'}, 
            3: {period: '08.12-02.01', subs: '28', nonsubs: '27', profile: '78', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 490, 
        src: require('../img/main/201.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '32', nonsubs: '27', profile: '80', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '31', nonsubs: '27', profile: '79', main: '-', other: '1'}, 
            3: {period: '08.12-02.01', subs: '31', nonsubs: '28', profile: '81', main: '-', other: '1'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 491, 
        src: require('../img/main/202.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '28', nonsubs: '40', profile: '96', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '28', nonsubs: '39', profile: '95', main: '-', other: '1'}, 
            3: {period: '08.12-02.01', subs: '29', nonsubs: '42', profile: '99', main: '-', other: '3'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 492, 
        src: require('../img/main/203.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '32', nonsubs: '36', profile: '90', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '31', nonsubs: '35', profile: '88', main: '-', other: '-'}, 
            3: {period: '08.12-02.01', subs: '31', nonsubs: '37', profile: '91', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 493, 
        src: require('../img/main/204.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '27', nonsubs: '36', profile: '80', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '26', nonsubs: '35', profile: '78', main: '-', other: '-'}, 
            3: {period: '08.12-02.01', subs: '26', nonsubs: '38', profile: '82', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    ////////
    {id: 494, 
        src: require('../img/main/205.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '29', nonsubs: '30', profile: '75', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '29', nonsubs: '29', profile: '74', main: '-', other: '1'}, 
            3: {period: '08.12-02.01', subs: '29', nonsubs: '32', profile: '79', main: '-', other: '1'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 495, 
        src: require('../img/main/206.jpg'), 
        w: '', 
        h: '', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '23', nonsubs: '19', profile: '48', main: '-', other: '-'}, 
            2: {period: '08.01', subs: '22', nonsubs: '19', profile: '47', main: '-', other: '-'}, 
            3: {period: '08.12-02.01', subs: '22', nonsubs: '21', profile: '50', main: '-', other: '-'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 496, 
        src: require('../img/main/208.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '27', nonsubs: '37', profile: '81', main: '-', other: '1'}, 
            2: {period: '08.01', subs: '27', nonsubs: '36', profile: '79', main: '-', other: '1'}, 
            3: {period: '08.12-02.01', subs: '27', nonsubs: '41', profile: '84', main: '-', other: '2'},
            4: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            5: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 497, 
        src: require('../img/main/209.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '15.01-30.01', subs: '27', nonsubs: '38', profile: '91', main: '-', other: '1'},
            2: {period: '08.01', subs: '26', nonsubs: '37', profile: '88', main: '-', other: '1'},
            3: {period: '02.01', subs: '26', nonsubs: '40', profile: '90', main: '-', other: '1'}, 
            4: {period: '28.11-02.12', subs: '28', nonsubs: '40', profile: '95', main: '-', other: '1'}, 
            5: {period: '23.11', subs: '28', nonsubs: '40', profile: '94', main: '-', other: '1'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 498, 
        src: require('../img/main/210.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '9', nonsubs: '12', profile: '22', main: '-', other: '-'},
            2: {period: '15.01-24.01', subs: '8', nonsubs: '12', profile: '21', main: '-', other: '-'},
            3: {period: '02.01-08.01', subs: '7', nonsubs: '12', profile: '20', main: '-', other: '-'}, 
            4: {period: '28.11-02.12', subs: '7', nonsubs: '10', profile: '18', main: '-', other: '-'}, 
            5: {period: '23.11', subs: '7', nonsubs: '10', profile: '17', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
    {id: 499, 
        src: require('../img/main/212.jpg'), 
        w: 'auto', 
        h: 'inherit', 
        text: '', 
        tags: '', 
        engagement: '-- -- --',
        currStatistic: {
            1: {period: '30.01', subs: '-', nonsubs: '-', profile: '-', main: '53', other: '-'},
            2: {period: '15.01-24.01', subs: '-', nonsubs: '-', profile: '-', main: '52', other: '-'},
            3: {period: '08.01', subs: '-', nonsubs: '-', profile: '-', main: '51', other: '-'}, 
            4: {period: '02.01', subs: '-', nonsubs: '-', profile: '-', main: '52', other: '-'}, 
            5: {period: '23.11-02.12', subs: '-', nonsubs: '-', profile: '51', main: '-', other: '-'},
            6: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            7: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
            8: {period: '-', subs: '-', nonsubs: '-', profile: '-', main: '-', other: '-'},
        }
    },
]